image: 'atlassian/default-image:4'
#image: node:16

pipelines:
  default:
    - step:
        name: Build and test the app
        image: 'node:latest'
        script:
          - npm install --legacy-peer-deps
          #- npm test
          - npm run build
  branches:
    deploy-s3:
      - step:
          name: Build and test the app
          image: 'node:latest'
          script:
            - npm install --legacy-peer-deps
            #- npm test
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploying the app to S3
          deployment: testing
          script:
            - pipe: 'atlassian/aws-s3-deploy:0.3.7'
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $TESTING_S3_BUCKET
                LOCAL_PATH: dist
                ACL: public-read
      - step:
          name: Invalidate cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.7.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $TESTING_CLOUDFRONT_DISTRIBUTION

    master:
      - step:
          name: Build and test the app
          image: 'node:latest'
          script:
            - npm install --legacy-peer-deps
            #- npm test
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploying the app to S3
          deployment: production
          script:
            - pipe: 'atlassian/aws-s3-deploy:0.3.7'
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $PRODUCTION_S3_BUCKET
                LOCAL_PATH: dist
                ACL: public-read
      - step:
          name: Invalidate cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.7.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $PRODUCTION_CLOUDFRONT_DISTRIBUTION