---
image: atlassian/default-image:4
pipelines:
  default:
    - step:
        name: Build and test the app
        image: node:20.8.1
        script:
          - npm install --legacy-peer-deps
          - npm run build:testing
  branches:
    testing:
      #- step:
      #    name: Build .env source file
      #    script:
      #      - echo export BASE_URL="https://testing-api.alchilazo.com.gt/api/" > build.env
      #    artifacts:
      #      - build.env
      - step:
          name: Build and test the app
          image: node:20.8.1
          script:
            - npm install --legacy-peer-deps
            - npm run build:testing
          artifacts:
            - dist/**
      - step:
          name: Deploying the app to S3
          deployment: testing
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $TESTING_S3_BUCKET
                LOCAL_PATH: dist
                ACL: public-read
      - step:
          name: Invalidate cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.7.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $TESTING_CLOUDFRONT_DISTRIBUTION
    master:
      - step:
          name: Build and test the app
          image: node:20.8.1
          script:
            - npm install --legacy-peer-deps
            - - npm run build:production
          artifacts:
            - dist/**
      - step:
          name: Deploying the app to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $PRODUCTION_S3_BUCKET
                LOCAL_PATH: dist
                ACL: public-read
      - step:
          name: Invalidate cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.7.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $PRODUCTION_CLOUDFRONT_DISTRIBUTION
